### PR TITLE
 Merge post SLE 12 SP1 release changes

### PR DESCRIPTION
**Pull request by imobach**
Merge `sle-12-sp1-after_release` in SP1 branch.

### CODE REVIEW

**Comment by ancorgs** [comment]
LGTM

**Comment by ancorgs** [comment]
Wait a moment. Wrong tab, I wanted to LGTM another PR.

**Comment by ancorgs** [comment]
Now I actually reviewed. LGTM (this time for real) :smile:

**Comment by imobach** [comment]
Thanks :) Also Travis is working again, so I'm merging right now.

**Pull request merged**
